# Generated by Django 4.0.5 on 2022-06-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxIdentificationNumber', models.CharField(max_length=12)),
                ('companyName', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
