# Generated by Django 4.0.5 on 2022-07-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationcontent',
            name='amountPaid',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationcontent',
            name='icaRetention',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationcontent',
            name='ivaRetention',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationcontent',
            name='rentaRetention',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationcontent',
            name='totalValueInvoice',
            field=models.CharField(max_length=20),
        ),
    ]
