# Generated by Django 4.0.5 on 2022-07-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notificationcontent_amountpaid'),
    ]

    operations = [
        migrations.CreateModel(
            name='controlEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customId', models.CharField(max_length=100)),
            ],
        ),
    ]
