# Generated by Django 4.0.5 on 2022-07-08 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_controlemails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlemails',
            old_name='customId',
            new_name='email',
        ),
    ]
